// // Mocks generated by Mockito 5.4.5 from annotations
// // in icy/test/auth/auth_repository_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i3;

// import 'package:icy/data/datasources/local_storage_service.dart' as _i4;
// import 'package:icy/data/models/user_model.dart' as _i5;
// import 'package:icy/services/api_service.dart' as _i2;
// import 'package:mockito/mockito.dart' as _i1;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: must_be_immutable
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class

// /// A class which mocks [ApiService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockApiService extends _i1.Mock implements _i2.ApiService {
//   MockApiService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i3.Future<void> init() =>
//       (super.noSuchMethod(
//             Invocation.method(#init, []),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<Map<String, dynamic>> login(String? email, String? password) =>
//       (super.noSuchMethod(
//             Invocation.method(#login, [email, password]),
//             returnValue: _i3.Future<Map<String, dynamic>>.value(
//               <String, dynamic>{},
//             ),
//           )
//           as _i3.Future<Map<String, dynamic>>);

//   @override
//   _i3.Future<Map<String, dynamic>> register(
//     String? name,
//     String? email,
//     String? password,
//     String? department,
//     String? avatarId,
//   ) =>
//       (super.noSuchMethod(
//             Invocation.method(#register, [
//               name,
//               email,
//               password,
//               department,
//               avatarId,
//             ]),
//             returnValue: _i3.Future<Map<String, dynamic>>.value(
//               <String, dynamic>{},
//             ),
//           )
//           as _i3.Future<Map<String, dynamic>>);

//   @override
//   _i3.Future<void> logout() =>
//       (super.noSuchMethod(
//             Invocation.method(#logout, []),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<Map<String, dynamic>> get(String? endpoint) =>
//       (super.noSuchMethod(
//             Invocation.method(#get, [endpoint]),
//             returnValue: _i3.Future<Map<String, dynamic>>.value(
//               <String, dynamic>{},
//             ),
//           )
//           as _i3.Future<Map<String, dynamic>>);

//   @override
//   _i3.Future<Map<String, dynamic>> post(
//     String? endpoint,
//     Map<String, dynamic>? data,
//   ) =>
//       (super.noSuchMethod(
//             Invocation.method(#post, [endpoint, data]),
//             returnValue: _i3.Future<Map<String, dynamic>>.value(
//               <String, dynamic>{},
//             ),
//           )
//           as _i3.Future<Map<String, dynamic>>);

//   @override
//   _i3.Future<Map<String, dynamic>> put(
//     String? endpoint,
//     Map<String, dynamic>? data,
//   ) =>
//       (super.noSuchMethod(
//             Invocation.method(#put, [endpoint, data]),
//             returnValue: _i3.Future<Map<String, dynamic>>.value(
//               <String, dynamic>{},
//             ),
//           )
//           as _i3.Future<Map<String, dynamic>>);
// }

// /// A class which mocks [LocalStorageService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockLocalStorageService extends _i1.Mock
//     implements _i4.LocalStorageService {
//   MockLocalStorageService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i3.Future<void> saveAuthUser(_i5.UserModel? user) =>
//       (super.noSuchMethod(
//             Invocation.method(#saveAuthUser, [user]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<_i5.UserModel?> getAuthUser() =>
//       (super.noSuchMethod(
//             Invocation.method(#getAuthUser, []),
//             returnValue: _i3.Future<_i5.UserModel?>.value(),
//           )
//           as _i3.Future<_i5.UserModel?>);

//   @override
//   _i3.Future<void> clearAuthUser() =>
//       (super.noSuchMethod(
//             Invocation.method(#clearAuthUser, []),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<void> saveData(String? key, dynamic value) =>
//       (super.noSuchMethod(
//             Invocation.method(#saveData, [key, value]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<dynamic> getData(String? key) =>
//       (super.noSuchMethod(
//             Invocation.method(#getData, [key]),
//             returnValue: _i3.Future<dynamic>.value(),
//           )
//           as _i3.Future<dynamic>);

//   @override
//   _i3.Future<void> removeData(String? key) =>
//       (super.noSuchMethod(
//             Invocation.method(#removeData, [key]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<void> clearAll() =>
//       (super.noSuchMethod(
//             Invocation.method(#clearAll, []),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);
// }
