name: icy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  forui: ^0.9.1+1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  blurrycontainer: ^2.1.0
  animations: ^2.0.11
  equatable: ^2.0.7
  url_launcher: ^6.3.1
  meta: ^1.16.0
  random_avatar: ^0.0.8
  path_provider: ^2.1.5
  path: ^1.8.3
  rive: ^0.13.20
  rive_animated_icon: ^2.0.3
  flutter_animated_icon_button: ^1.1.3
  lottie: ^3.3.1
  border_progress_indicator: ^0.0.3
  shared_preferences: ^2.5.2
  intl: ^0.19.0
  http: ^1.3.0
  image_picker: ^1.0.7
  http_parser: ^4.0.2
  permission_handler: ^11.3.0          
  timezone: ^0.10.0                     
  dio: ^5.3.2
  flutter_local_notifications: ^19.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  bloc_test: ^10.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/animations/tabs/

